# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sspapp:
    image: sspapp
    build:
      context: .
      dockerfile: SSP_app/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "8000:5011"
      - "8001:5012"
    environment:
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5011
      - ASPNETCORE_HTTPS_PORTS=5012
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Passw0rd
    volumes:
      - /home/lobadk/.aspnet/https:/https/
      - ~/.vsdbg:/remote_debugger:rw
