// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace SSP_app.Migrations.TodoDb
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("TodoApp.Data.Cpr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CprNr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__Cpr__3214EC07F9689AA0");

                    b.ToTable("Cpr", (string)null);
                });

            modelBuilder.Entity("TodoApp.Data.TodoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__TodoList__3214EC07DA7A60E9");

                    b.HasIndex("UserId");

                    b.ToTable("TodoList", (string)null);
                });

            modelBuilder.Entity("TodoApp.Data.TodoList", b =>
                {
                    b.HasOne("TodoApp.Data.Cpr", "User")
                        .WithMany("TodoLists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Todolist_Cpr");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoApp.Data.Cpr", b =>
                {
                    b.Navigation("TodoLists");
                });
#pragma warning restore 612, 618
        }
    }
}
